import 'package:share_plus/share_plus.dart';
import '../features/transactions/models/expense_model.dart';
import '../features/transactions/models/income_model.dart';
import '../utils/formatters.dart';

class ShareService {
  static Future<void> shareDailySummary({
    required DateTime date,
    List<IncomeModel> incomes = const [],
    List<ExpenseModel> expenses = const [],
  }) async {
    final totalIncome = incomes.fold(0.0, (sum, item) => sum + item.amount);
    final totalExpense = expenses.fold(0.0, (sum, item) => sum + item.amount);
    final profit = totalIncome - totalExpense;

    final message = '''
📊 *Hotel Expense Tracker - Daily Summary*
📅 Date: ${Formatters.formatDateFull(date)}

💰 *Income*
${_formatIncomeDetails(incomes)}
   • *Total Income:* ${Formatters.formatCurrency(totalIncome)}

🛒 *Expenses*
${_formatExpenseDetails(expenses)}
   • *Total Expense:* ${Formatters.formatCurrency(totalExpense)}

${profit >= 0 ? '✅' : '❌'} *${profit >= 0 ? 'Profit' : 'Loss'}:* ${Formatters.formatCurrency(profit.abs())}

---
Generated by Hotel Expense Tracker
    ''';

    await Share.share(
      message,
      subject: 'Daily Summary - ${Formatters.formatDate(date)}',
    );
  }

  static Future<void> shareWeeklySummary({
    required DateTime startDate,
    required DateTime endDate,
    required double totalIncome,
    required double totalExpense,
    required int totalMeals,
    required int profitableDays,
  }) async {
    final profit = totalIncome - totalExpense;
    final avgDailyProfit = profit / 7;

    final message = '''
📊 *Hotel Expense Tracker - Weekly Summary*
📅 Period: ${Formatters.formatDate(startDate)} - ${Formatters.formatDate(endDate)}

💰 *Total Income:* ${Formatters.formatCurrency(totalIncome)}
🛒 *Total Expense:* ${Formatters.formatCurrency(totalExpense)}
${profit >= 0 ? '✅' : '❌'} *${profit >= 0 ? 'Profit' : 'Loss'}:* ${Formatters.formatCurrency(profit.abs())}

📈 *Statistics*
   • Average Daily Profit: ${Formatters.formatCurrency(avgDailyProfit)}
   • Profitable Days: $profitableDays/7
   • Total Meals: $totalMeals

---
Generated by Hotel Expense Tracker
    ''';

    await Share.share(
      message,
      subject: 'Weekly Summary',
    );
  }

  static Future<void> shareMonthlySummary({
    required String month,
    required double totalIncome,
    required double totalExpense,
    required int totalMeals,
    required int profitableDays,
    required int totalDays,
  }) async {
    final profit = totalIncome - totalExpense;
    final avgDailyProfit = totalDays > 0 ? profit / totalDays : 0;

    final message = '''
📊 *Hotel Expense Tracker - Monthly Summary*
📅 Month: $month

💰 *Total Income:* ${Formatters.formatCurrency(totalIncome)}
🛒 *Total Expense:* ${Formatters.formatCurrency(totalExpense)}
${profit >= 0 ? '✅' : '❌'} *${profit >= 0 ? 'Profit' : 'Loss'}:* ${Formatters.formatCurrency(profit.abs())}

📈 *Statistics*
   • Average Daily Profit: ${Formatters.formatCurrency(avgDailyProfit.toDouble())}
   • Profitable Days: $profitableDays/$totalDays
   • Total Meals: $totalMeals
   • Success Rate: ${(profitableDays / totalDays * 100).toStringAsFixed(1)}%

---
Generated by Hotel Expense Tracker
    ''';

    await Share.share(
      message,
      subject: 'Monthly Summary - $month',
    );
  }

  static String _formatExpenseDetails(List<ExpenseModel> expenses) {
    if (expenses.isEmpty) return '   • No expenses recorded\n';

    final Map<String, double> categorySums = {};
    for (var e in expenses) {
      final category = e.categoryName ?? 'Other';
      categorySums[category] = (categorySums[category] ?? 0) + e.amount;
    }

    final sortedCategories = categorySums.keys.toList()..sort();
    final details = sortedCategories.map((cat) {
      return '   • $cat: ${Formatters.formatCurrency(categorySums[cat]!)}';
    }).toList();

    return '${details.join('\n')}\n';
  }

  static String _formatIncomeDetails(List<IncomeModel> incomes) {
    if (incomes.isEmpty) return '   • No income recorded\n';

    final Map<String, double> categorySums = {};
    for (var i in incomes) {
      final category = i.categoryName ?? 'Other';
      categorySums[category] = (categorySums[category] ?? 0) + i.amount;
    }

    final sortedCategories = categorySums.keys.toList()..sort();
    final details = sortedCategories.map((cat) {
      return '   • $cat: ${Formatters.formatCurrency(categorySums[cat]!)}';
    }).toList();

    return '${details.join('\n')}\n';
  }
}
