import 'package:share_plus/share_plus.dart';
import '../models/income.dart';
import '../models/expense.dart';
import '../utils/formatters.dart';

class ShareService {
  static Future<void> shareDailySummary({
    required DateTime date,
    Income? income,
    Expense? expense,
  }) async {
    final totalIncome =
        (income?.onlineIncome ?? 0) + (income?.offlineIncome ?? 0);
    final totalExpense = _calculateTotalExpense(expense);
    final profit = totalIncome - totalExpense;
    final mealsCount = income?.mealsCount ?? 0;

    final message = '''
📊 *Hotel Expense Tracker - Daily Summary*
📅 Date: ${Formatters.formatDateFull(date)}

💰 *Income*
   • Online: ${Formatters.formatCurrency(income?.onlineIncome ?? 0)}
   • Offline: ${Formatters.formatCurrency(income?.offlineIncome ?? 0)}
   • *Total Income:* ${Formatters.formatCurrency(totalIncome)}

🛒 *Expenses*
${_formatExpenseDetails(expense)}
   • *Total Expense:* ${Formatters.formatCurrency(totalExpense)}

${profit >= 0 ? '✅' : '❌'} *${profit >= 0 ? 'Profit' : 'Loss'}:* ${Formatters.formatCurrency(profit.abs())}

🍽️ Meals Served: $mealsCount

${income?.notes != null && income!.notes!.isNotEmpty ? '📝 Notes: ${income.notes}\n' : ''}
---
Generated by Hotel Expense Tracker
    ''';

    await Share.share(
      message,
      subject: 'Daily Summary - ${Formatters.formatDate(date)}',
    );
  }

  static Future<void> shareWeeklySummary({
    required DateTime startDate,
    required DateTime endDate,
    required double totalIncome,
    required double totalExpense,
    required int totalMeals,
    required int profitableDays,
  }) async {
    final profit = totalIncome - totalExpense;
    final avgDailyProfit = profit / 7;

    final message = '''
📊 *Hotel Expense Tracker - Weekly Summary*
📅 Period: ${Formatters.formatDate(startDate)} - ${Formatters.formatDate(endDate)}

💰 *Total Income:* ${Formatters.formatCurrency(totalIncome)}
🛒 *Total Expense:* ${Formatters.formatCurrency(totalExpense)}
${profit >= 0 ? '✅' : '❌'} *${profit >= 0 ? 'Profit' : 'Loss'}:* ${Formatters.formatCurrency(profit.abs())}

📈 *Statistics*
   • Average Daily Profit: ${Formatters.formatCurrency(avgDailyProfit)}
   • Profitable Days: $profitableDays/7
   • Total Meals: $totalMeals

---
Generated by Hotel Expense Tracker
    ''';

    await Share.share(
      message,
      subject: 'Weekly Summary',
    );
  }

  static Future<void> shareMonthlySummary({
    required String month,
    required double totalIncome,
    required double totalExpense,
    required int totalMeals,
    required int profitableDays,
    required int totalDays,
  }) async {
    final profit = totalIncome - totalExpense;
    final avgDailyProfit = totalDays > 0 ? profit / totalDays : 0;

    final message = '''
📊 *Hotel Expense Tracker - Monthly Summary*
📅 Month: $month

💰 *Total Income:* ${Formatters.formatCurrency(totalIncome)}
🛒 *Total Expense:* ${Formatters.formatCurrency(totalExpense)}
${profit >= 0 ? '✅' : '❌'} *${profit >= 0 ? 'Profit' : 'Loss'}:* ${Formatters.formatCurrency(profit.abs())}

📈 *Statistics*
   • Average Daily Profit: ${Formatters.formatCurrency(avgDailyProfit.toDouble())}
   • Profitable Days: $profitableDays/$totalDays
   • Total Meals: $totalMeals
   • Success Rate: ${(profitableDays / totalDays * 100).toStringAsFixed(1)}%

---
Generated by Hotel Expense Tracker
    ''';

    await Share.share(
      message,
      subject: 'Monthly Summary - $month',
    );
  }

  static double _calculateTotalExpense(Expense? expense) {
    if (expense == null) return 0.0;

    return expense.fish +
        expense.meat +
        expense.chicken +
        expense.milk +
        expense.parotta +
        expense.pathiri +
        expense.dosa +
        expense.appam +
        expense.coconut +
        expense.vegetables +
        expense.rice +
        expense.laborManisha +
        expense.laborMidhun +
        expense.others;
  }

  static String _formatExpenseDetails(Expense? expense) {
    if (expense == null) return '   • No expenses recorded\n';

    final details = <String>[];

    if (expense.fish > 0) {
      details.add('   • Fish: ${Formatters.formatCurrency(expense.fish)}');
    }
    if (expense.meat > 0) {
      details.add('   • Meat: ${Formatters.formatCurrency(expense.meat)}');
    }
    if (expense.chicken > 0) {
      details
          .add('   • Chicken: ${Formatters.formatCurrency(expense.chicken)}');
    }
    if (expense.milk > 0) {
      details.add('   • Milk: ${Formatters.formatCurrency(expense.milk)}');
    }
    if (expense.parotta > 0) {
      details
          .add('   • Parotta: ${Formatters.formatCurrency(expense.parotta)}');
    }
    if (expense.pathiri > 0) {
      details
          .add('   • Pathiri: ${Formatters.formatCurrency(expense.pathiri)}');
    }
    if (expense.dosa > 0) {
      details.add('   • Dosa: ${Formatters.formatCurrency(expense.dosa)}');
    }
    if (expense.appam > 0) {
      details.add('   • Appam: ${Formatters.formatCurrency(expense.appam)}');
    }
    if (expense.coconut > 0) {
      details
          .add('   • Coconut: ${Formatters.formatCurrency(expense.coconut)}');
    }
    if (expense.vegetables > 0) {
      details.add(
          '   • Vegetables: ${Formatters.formatCurrency(expense.vegetables)}');
    }
    if (expense.rice > 0) {
      details.add('   • Rice: ${Formatters.formatCurrency(expense.rice)}');
    }
    if (expense.laborManisha > 0) {
      details.add(
          '   • Labor Manisha: ${Formatters.formatCurrency(expense.laborManisha)}');
    }
    if (expense.laborMidhun > 0) {
      details.add(
          '   • Labor Midhun: ${Formatters.formatCurrency(expense.laborMidhun)}');
    }
    if (expense.others > 0) {
      details.add('   • Others: ${Formatters.formatCurrency(expense.others)}');
    }

    return details.isEmpty
        ? '   • No expenses recorded\n'
        : '${details.join('\n')}\n';
  }
}
